Issues
LinkNacional/whmcs-addon pull request #17
Opened 2021-03-15 16:32 UTC by JoaoVictorLNacional

2021-03-15 17:09 UTC, souzadavi approved these changes

2021-03-15 17:14 UTC, souzadavi requested changes
Por favor verificar as observações.

2021-03-15 17:14 UTC, souzadavi commented on modules/addons/gofasnfeio/functions.php
>      header('Content-Disposition: attachment; filename="default-filename.txt"');
@JoaoVictorLNacional por favor alterar o nome do arquivo para algo mais adequado: log-whmcs-nfe.txt

2021-03-15 17:14 UTC, souzadavi commented on modules/addons/gofasnfeio/sendNFE.php
> +    if ($params['email_nfe']) {
@JoaoVictorLNacional não entendi essa condição. Porque esta definindo como vazio o endereço do email? tecnicamente todos os clientes tem endereço de email cadastrado

2021-03-15 17:24 UTC, JoaoVictorLNacional commented on modules/addons/gofasnfeio/sendNFE.php
> +    if ($params['email_nfe']) {
nas configurações do modulo tem um checkbox Disparar e-mail com a nota que envia a nota para o usuário
ai quem faz esse disparo é a API,então se não tiver marcado não envia o e-mail pra não disparar pro usuário

2021-03-15 17:24 UTC, JoaoVictorLNacional commented on modules/addons/gofasnfeio/functions.php
>      header('Content-Disposition: attachment; filename="default-filename.txt"');
corrigido

2021-03-15 17:59 UTC, souzadavi approved these changes

2021-03-15 17:59 UTC, souzadavi commented on modules/addons/gofasnfeio/callback.php
>      } else {
@JoaoVictorLNacional se esta dando um else da negação do $post o que vc eta esperando salvar no log?

2021-03-16 13:19 UTC, JoaoVictorLNacional commented on modules/addons/gofasnfeio/callback.php
>      } else {
se deu um erro ou não
ele salva com ERROR ai fica mais fácil identificar

2021-03-16 13:19 UTC, merged